version: "3.9"

services:

  backend:
    build: ./evote-backend
    volumes:
      - uploads:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST} 
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:587}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME} 
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD} 
      SMTP_AUTH: ${SMTP_AUTH} 
      STARTTLS_ENABLE: ${STARTTLS_ENABLE}
    depends_on:
      - db

  frontend:
    build: ./evote-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: evote_db
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  uploads:
